version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9595:9595"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - GUNICORN_CMD_ARGS="--reload"
      - DATABASE_URL=postgresql://neighborgoods:neighborgoods@db:5432/neighborgoods
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=neighborgoods
      - POSTGRES_PASSWORD=neighborgoods
      - POSTGRES_DB=neighborgoods
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
